config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]

  get 'sushis/maguro' => 'sushis#maguro'
  get 'sushis/salmon' => 'sushis#salmon'
  get 'sushis/saba' => 'sushis#saba'

  resources :sushis do
    resources :likes, only: [:create, :destroy]
  end 
  root 'sushis#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :sushi
  belongs_to :user

  validates_uniqueness_of :sushi_id, scope: :user_id

end

app/models/sushi.rb
class Sushi < ApplicationRecord
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user


    mount_uploader :image, ImageUploader
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sushis, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_sushis, through: :likes, source: :sushi

  def already_liked?(sushi)
    self.likes.exists?(sushi_id: sushi.id)
  end

  validates :name, presence: true
  validates :profile, length: { maximum: 200 } 

  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(sushi_id: params[:sushi_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(sushi_id: params[:sushi_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end

end

app/controllers/sushis_controller.rb
class SushisController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create]  

  def maguro
    @sushis = Sushi.all
  end

  def salmon
    @sushis = Sushi.all
  end

  def saba
    @sushis = Sushi.all
  end

    def index
        @sushis = Sushi.all

        if params[:search] == nil
          @sushis= Sushi.all
        elsif params[:search] == ''
          @sushis= Sushi.all
        else

          @sushis = Sushi.where("sushiname LIKE ? ",'%' + params[:search] + '%')
        end

        @sushis = @sushis.page(params[:page]).per(3)
    end

    def new
        @sushi = Sushi.new
      end
    
      def create
        sushi = Sushi.new(sushi_params)

        sushi.user_id = current_user.id

        if sushi.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @sushi = Sushi.find(params[:id])
      end

      def edit
        @sushi = Sushi.find(params[:id])
      end

      def update
        sushi = Sushi.find(params[:id])
        if sushi.update(sushi_params)
          redirect_to :action => "show", :id => sushi.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        sushi = Sushi.find(params[:id])
        sushi.destroy
        redirect_to action: :index
      end

     

      private
      def sushi_params
        params.require(:sushi).permit(:sushiname, :highlight,:category, :image)
      end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sushis_helper.rb
module SushisHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sushisearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3cfee1ed0a.js"  crossorigin="anonymous"></script> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
   <h1><%= link_to "すしサーチ", sushis_path %></h1>
   <div class="header-list">
    <ul>
      
      <li><%= link_to "新規投稿",new_sushi_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "ログイン", new_user_session_path %></li>
     <% end %>
    </ul>
   </div>
  </header>

  <main>
   <%= yield %>
  </main>

  <footer>
    <p>Copyright © GeekSalon All Rights Reserved.</p>
  </footer>
  </body>
</html>

app/views/sushis/edit.html.erb
<%= form_for @sushi do |f| %>
    <%= f.label :寿司ネタの名前 %>
    <%= f.text_field :sushiname, :size => 140 %> 
    <%= f.label :おいしさの説明 %>
    <%= f.text_field :highlight, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/sushis/index.html.erb
<div class="breadcrumb">
<ol itemscope itemtype="https://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
    <a itemprop="item" href="http://localhost:3000/sushis">
        <h2><span itemprop="name">HOME</span></h2>
    </a>
    <meta itemprop="position" content="1" />
  </li>
</ol>


<div class="sushi-search-box">
  <h3>寿司ネタを検索</h3>
  <%= form_tag({controller:"sushis",action:"index"}, method: :get) do %>
    <%= text_field_tag :search ,"",{class:"searchbox"} %>
    <%= submit_tag '検索'  %>
  <% end %>
</div>

<%= image_tag "maguro.jpeg", class: "picture" %>

<div class="home">
<h4>人気の寿司ネタはこちら▼</h4>

  <div class="tobigbox">
    <div class="tosalmon">
        <p><%= link_to "サーモン一覧へ", sushis_salmon_path %></p>
    </div>

    <div class="tosaba">
        <p><%= link_to "さば一覧へ", sushis_saba_path %></p>
    </div>

    <div class="tomaguro">
        <p><%= link_to "まぐろ一覧へ", sushis_maguro_path %></p>
    </div>
 </div>

<div class="toppage4bigbox"



  <div class="sushis-container">
  <% if user_signed_in? %>
  </div>

  <%= link_to "マイページへ", user_path(current_user.id) %>
  <% end %>

</div>

<div class="sushilistbox">
  <%= page_entries_info @sushis %>
  <%= paginate @sushis %>



  <% @sushis.each do |t| %>
    <div class="sushipostbox"
      <div class="sushi">
      <div class="username">
        <%= link_to t.user.name, user_path(t.user.id) %>
      </div>

      <div class="sushiimage">
        <%= image_tag t.image_url, size: "100x50" if t.image? %>
      </div>

      <div class="sushiname">
        <%= t.sushiname %>
      </div>

      <div class="highlight">
        <%= t.highlight %>
      </div>

      <div class="sushibottom">

        <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= link_to sushi_like_path(id: t.id, sushi_id: t.id), method: :delete do %>
              <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= link_to sushi_likes_path(id: t.id, sushi_id: t.id), method: :post do %>
              <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= t.likes.count %>
    <% end %>

        <%= link_to "詳細へ", sushi_path(t.id) %>
        <% if t.category == "maguro" %>
        <%= link_to "まぐろ一覧へ", sushis_maguro_path %>
        <% end %>
        <% if t.category == "salmon" %>
        <%= link_to "サーモン一覧へ", sushis_salmon_path %>
        <% end %>
        <% if t.category == "saba" %>
        <%= link_to "さば一覧へ", sushis_saba_path %>
        <% end %>

        <% if user_signed_in? && current_user.id == t.user_id %>
        <%= link_to "編集する", edit_sushi_path(t.id) %>
        <%= link_to "削除する", sushi_path(t.id), method: :delete %>
      <% end %> 
      
      </div>

      </div>
  
      <% end %>

  </div>

</div>

app/views/sushis/maguro.html.erb
<div class="breadcrumb">
<ol itemscope itemtype="https://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
    <a itemprop="item" href="/sushis">
        <span itemprop="name">HOME</span>
    </a>
    <meta itemprop="position" content="1" />
  </li>

  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
    
    <a itemprop="item" href="/sushis/maguro">
        <span itemprop="name">まぐろ一覧</span>
    </a>
    <meta itemprop="position" content="2" />
  </li>

</ol>

<h1>まぐろ一覧</h1>

<%= image_tag "maguro.jpeg", class: "picture" %>

<div class="magurobox1">

  <div class="magurotaste">
    【味】★★★☆☆
  </div>

  <div class="magurotexture">
    【食感】★★☆☆☆
  </div>

</div>

<div class="magurobox2">

  <div class="maguromini1">

    <div class="magurodetail">
    【詳細情報】
    <p>
    まぐろは美味いです。
    </p>
    </div>

    <div class="maguroad">
    ＃広告もどき（画像載せる）
    </div>

  </div>

  <div class="maguromini2">
    【人気の投稿】

    <% @sushis.each do |t| %>
      <% if t.category == "maguro" %>  
      <p>寿司ネタの名前:<%= t.sushiname %></p>
      <p>おいしさの説明:<%= t.highlight %></p>
      <%= image_tag t.image_url, size: "150x100" if t.image? %>
      <% end %>
    <% end %>
      
  </div>

</div>



  

app/views/sushis/new.html.erb
<div class="breadcrumb">
<ol itemscope itemtype="https://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
    <a itemprop="item" href="/sushis">
        <span itemprop="name">HOME</span>
    </a>
    <meta itemprop="position" content="1" />
  </li>

  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
    
    <a itemprop="item" href="/sushis/new">
        <span itemprop="name">新規投稿</span>
    </a>
    <meta itemprop="position" content="2" />
  </li>

</ol>

<h1>新規投稿</h1>
<h3>好きな寿司ネタを投稿しよう！</h3>
<%= form_for @sushi do |f| %>

  <div class="field">
    <%= f.label :寿司ネタの名前 %>
    <%= f.text_field :sushiname, :size => 30 %>
  </div>

  <%= f.select :category, [ ["サーモン", "salmon"], ["さば", "saba"], ["まぐろ", "maguro"]], include_blank: "カテゴリー選択" %>

  <div class="field">
    <%= f.label :おいしさの説明  %>
    <%= f.text_area :highlight, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :寿司ネタの画像 %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "マイページへ", user_path(current_user.id) %>

app/views/sushis/saba.html.erb
<h1>さば一覧</h1>
<% @sushis.each do |t| %>
  <% if t.category == "saba" %>  
  <p>寿司ネタの名前:<%= t.sushiname %></p>
  <p>おいしさの説明:<%= t.highlight %></p>
  <%= image_tag t.image_url, size: "150x100" if t.image? %>
  <% end %>
  
<% end %>

app/views/sushis/salmon.html.erb
<h1>サーモン一覧</h1>
<% @sushis.each do |t| %>
  <% if t.category == "salmon" %> 
  <p>寿司ネタの名前:<%= t.sushiname %></p>
  <p>おいしさの説明:<%= t.highlight %></p>
  <%= image_tag t.image_url, size: "150x100" if t.image? %>
  <% end %>

<% end %>

app/views/sushis/show.html.erb
<h1>にぎり</h1>
<h3>投稿詳細</h3>
<div class="sushi">
  <p><%= @sushi.sushiname %></p>
  <p><%= @sushi.highlight %></p>

  <% if user_signed_in? %>
      <% if current_user.already_liked?(@sushi) %>
        <%= link_to sushi_like_path(@sushi), method: :delete do %>
          <i class="fas fa-heart"></i><%= @sushi.likes.count %>
        <% end %>
      <% else %>
        <%= link_to sushi_likes_path(@sushi), method: :post do %>
          <i class="far fa-heart"></i><%= @sushi.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @sushi.likes.count %>
    <% end %>


 <% if user_signed_in? && current_user.id == @sushi.user_id %>
  <%= link_to "編集する", edit_sushi_path(@sushi.id) %>
  <%= button_to "削除する", sushi_path(@sushi.id), method: :delete %> 
 <% end %> 
</div>

<h2>いいねしたユーザー</h2>
<% @sushi.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= image_tag @sushi.image_url, size: "150x100" if @sushi.image? %>

<%= link_to "一覧に戻る", sushis_path %>

<% if @sushi.category == "maguro" %>  
 <%= link_to "まぐろ一覧へ", sushis_maguro_path %>
<% end %>

<% if @sushi.category == "salmon" %>  
 <%= link_to "サーモン一覧へ", sushis_salmon_path %>
<% end %>

<% if @sushi.category == "saba" %>  
 <%= link_to "さば一覧へ", sushis_saba_path %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "初めての方はこちら", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="breadcrumb">
<ol itemscope itemtype="https://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
    <a itemprop="item" href="http://localhost:3000/sushis">
        <span itemprop="name">HOME</span>
    </a>
    <meta itemprop="position" content="1" />
  </li>

  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
    
    <a itemprop="item" href="http://localhost:3000/users/3">
        <span itemprop="name">マイページ</span>
    </a>
    <meta itemprop="position" content="2" />
  </li>

</ol>

<div class="mypagemini1">
  <h1>マイページ</h1>
  <p>名前 : <%= @user.name %></p>
  <%= image_tag @user.image_url, size: "100x50" if @user.image? %>

  <p>メールアドレス : <%= @user.email %></p>
  <p>プロフィール文 : <%= @user.profile %></p>

  <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path %>
  <% end %>

</div>

<div class="mypagemini2">
  <h2>ユーザーの投稿一覧</h2>

  <%= link_to "新規投稿をする", new_sushi_path %>

  <% @user.sushis.each do |t| %>
    <%= t.sushiname %>
  <% end %>

  
</div>